name: 'Approval and Webhook Action'
description: ''

inputs:
  app:
    description: 'The name of the application.'
    required: true
  app_version:
    description: 'The version of the application.'
    required: true
  short_sha:
    description: 'The short SHA of the Git commit.'
    required: true
  gh_pat:
    description: "GitHub Personal Access Token"
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Parse CODEOWNERS from .github folder
      id: codeowners  
      run: |
        CODEOWNERS_FILE=".github/CODEOWNERS"
        if [ ! -f "$CODEOWNERS_FILE" ]; then
          echo " CODEOWNERS file not found in .github/"
          exit 1
        fi

        # Extract approvers from CODEOWNERS
        APPROVERS=$(grep -o '@[^ ]*' "$CODEOWNERS_FILE" | sed 's/@//g' | paste -sd "," -)
        echo "Approvers found: $APPROVERS"
        # Save output
        echo "approvers=$APPROVERS" >> $GITHUB_OUTPUT
      shell: bash
    
    - name: Approval
      uses: trstringer/manual-approval@v1
      with:
        secret: "${{ inputs.gh_pat }}"
        approvers: "${{ steps.codeowners.outputs.approvers }},devops-it"
        minimum-approvals: 1
        issue-title: "${{ inputs.app }} Deploying version ${{ inputs.app_version }}-${{ inputs.short_sha }}"
        issue-body: "Please approve or deny the deployment of version ${{ inputs.app_version }}-${{ inputs.short_sha }}."
        exclude-workflow-initiator-as-approver: false
        fail-on-denial: true
        additional-approved-words: ''
        additional-denied-words: ''
        polling-interval-seconds: 10